INFO:     Started server process [30067]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2025-01-16 01:53:08,907 - INFO - Received search request: search_terms=['software company barcelona', 'tech startup madrid', 'digital agency spain'] num_results=5 ignore_previously_fetched=True optimize_english=False optimize_spanish=True shuffle_keywords=True language='ES' enable_email_sending=False from_email=None reply_to=None email_template_id=None
2025-01-16 01:53:08,907 - INFO - Shuffled search term: software company barcelona
2025-01-16 01:53:08,907 - INFO - Optimized search term: "software company barcelona" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:53:08,907 - INFO - Starting search for query: "software company barcelona" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:53:12,404 - INFO - Found 5 results
2025-01-16 01:53:12,404 - INFO - Found 5 URLs for term: "software company barcelona" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:53:12,404 - INFO - Processing URL: https://guiaisv.channelpartner.es/tranxfer-software-company/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'guiaisv.channelpartner.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:13,670 - INFO - Found 3 emails in https://guiaisv.channelpartner.es/tranxfer-software-company/
2025-01-16 01:53:13,670 - INFO - Processing valid email: sergio.real@bps.com.es
2025-01-16 01:53:13,675 - INFO - Extracted info - Name: , Company: GuiaISV, Job: 
2025-01-16 01:53:14,084 - INFO - Added new lead: sergio.real@bps.com.es
2025-01-16 01:53:14,084 - INFO - Processing valid email: info@bps.com.es
2025-01-16 01:53:14,084 - INFO - Processing valid email: info@tranxfer.com
2025-01-16 01:53:14,084 - INFO - Processing URL: https://aubay.es/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'aubay.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:15,645 - INFO - Found 2 emails in https://aubay.es/
2025-01-16 01:53:15,645 - INFO - Processing valid email: contacto@aubay.mx
2025-01-16 01:53:15,655 - INFO - Extracted info - Name: Contacta, Company: AUBAY, Job: Nuestros equipos de expertos, desarrolladores, ingenieros, arquitectos, jefes de proyecto, consultores e incluso gerentes lo esperan para reforzar los equipos de Aubay y trabajar en proyectos innovadores, atractivos y tecnológicamente estimulantes.
2025-01-16 01:53:16,040 - INFO - Added new lead: contacto@aubay.mx
2025-01-16 01:53:16,040 - INFO - Processing valid email: comunicacion@aubay.es
2025-01-16 01:53:16,040 - INFO - Processing URL: https://themailcompany.es/contacto/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'themailcompany.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:16,402 - INFO - Found 3 emails in https://themailcompany.es/contacto/
2025-01-16 01:53:16,402 - INFO - Processing valid email: hola@themailcompany.es
2025-01-16 01:53:16,416 - INFO - Extracted info - Name: Contacto, Company: The Mail Company, Job: 
2025-01-16 01:53:16,813 - INFO - Added new lead: hola@themailcompany.es
2025-01-16 01:53:16,813 - INFO - Processing valid email: hola@Themailcompany.es
2025-01-16 01:53:16,813 - INFO - Processing valid email: 91Mailhola@themailcompany.esBARCELONAParque
2025-01-16 01:53:16,813 - INFO - Processing URL: https://www.pagepersonnel.es/contactos/barcelona
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.pagepersonnel.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:18,295 - INFO - Found 1 emails in https://www.pagepersonnel.es/contactos/barcelona
2025-01-16 01:53:18,295 - INFO - Processing valid email: gdpr@pagegroup.eu
2025-01-16 01:53:18,304 - INFO - Extracted info - Name: Contacto, Company: Page Personnel, Job: 
2025-01-16 01:53:18,702 - INFO - Added new lead: gdpr@pagegroup.eu
2025-01-16 01:53:18,702 - INFO - Processing URL: https://www.grupocastilla.es/contacto/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.grupocastilla.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:19,901 - INFO - Found 1 emails in https://www.grupocastilla.es/contacto/
2025-01-16 01:53:19,901 - INFO - Processing valid email: info@grupocastilla.es
2025-01-16 01:53:19,912 - INFO - Extracted info - Name: Contacto, Company: Grupo Castilla, Job: 
2025-01-16 01:53:20,320 - INFO - Added new lead: info@grupocastilla.es
2025-01-16 01:53:20,320 - INFO - Shuffled search term: tech madrid startup
2025-01-16 01:53:20,320 - INFO - Optimized search term: "tech madrid startup" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:53:20,320 - INFO - Starting search for query: "tech madrid startup" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:53:23,479 - INFO - Found 5 results
2025-01-16 01:53:23,479 - INFO - Found 5 URLs for term: "tech madrid startup" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:53:23,479 - INFO - Processing URL: https://asociacionstartups.es/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'asociacionstartups.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:26,929 - INFO - Found 0 emails in https://asociacionstartups.es/
2025-01-16 01:53:26,929 - INFO - Processing URL: https://www.madridinnovation.es/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.madridinnovation.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:29,669 - INFO - Found 0 emails in https://www.madridinnovation.es/
2025-01-16 01:53:29,670 - INFO - Processing URL: https://coworkingonline.es/swmadrid/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'coworkingonline.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:32,151 - INFO - Found 2 emails in https://coworkingonline.es/swmadrid/
2025-01-16 01:53:32,151 - INFO - Processing valid email: startups@miro.comGoDaddy
2025-01-16 01:53:32,161 - INFO - Extracted info - Name: , Company: COWORKING ONLINE by Fangaloka, Job: CEO, 3webd
2025-01-16 01:53:32,557 - INFO - Added new lead: startups@miro.comGoDaddy
2025-01-16 01:53:32,557 - INFO - Processing valid email: support@porkbun.com.Patrocinador
2025-01-16 01:53:32,557 - INFO - Processing URL: https://mavens.es/launchevent
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mavens.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:33,481 - INFO - Found 1 emails in https://mavens.es/launchevent
2025-01-16 01:53:33,481 - INFO - Processing valid email: que.necesitas@mavens.es
2025-01-16 01:53:33,486 - INFO - Extracted info - Name: , Company: Tech Spain Advocates Launch Event | Mavens, Job: 
2025-01-16 01:53:33,873 - INFO - Added new lead: que.necesitas@mavens.es
2025-01-16 01:53:33,873 - INFO - Processing URL: https://www.creatit.es/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.creatit.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:34,641 - INFO - Found 1 emails in https://www.creatit.es/
2025-01-16 01:53:34,641 - INFO - Processing valid email: hello@creatit.es
2025-01-16 01:53:34,656 - INFO - Extracted info - Name: Contacto., Company: creatit | Agencia de Marketing Digital, Pymes, StartUps y grandes empresas en Madrid, Job: El Facebook Business Manager es una herramienta poderosa pero a menudo desconocida para muchos emprendedores y profesionales. En esta guía, te mostraremos cómo aprovechar al máximo esta plataforma y configurarla correctamente para impulsar tu presencia en Facebook e Instagram. ¡Vamos a sumergirnos en los detalles!
2025-01-16 01:53:35,203 - INFO - Added new lead: hello@creatit.es
2025-01-16 01:53:35,204 - INFO - Shuffled search term: agency digital spain
2025-01-16 01:53:35,204 - INFO - Optimized search term: "agency digital spain" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:53:35,204 - INFO - Starting search for query: "agency digital spain" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:53:38,406 - INFO - Found 5 results
2025-01-16 01:53:38,406 - INFO - Found 5 URLs for term: "agency digital spain" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:53:38,406 - INFO - Processing URL: https://inspiraagency.es/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'inspiraagency.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:44,816 - INFO - Found 1 emails in https://inspiraagency.es/
2025-01-16 01:53:44,817 - INFO - Processing valid email: giancarlo.milone@inspiraagency.es
2025-01-16 01:53:44,828 - INFO - Extracted info - Name: , Company: Inspira Agency, Job: Autorizo a contactarme comercialmente por email, teléfono y/o vía Whatsapp sobre los servicios y productos relativos al marketing digital y directorios, así como elaborar perfiles del negocio y recabar información a través de tecnologías de seguimiento.
2025-01-16 01:53:45,222 - INFO - Added new lead: giancarlo.milone@inspiraagency.es
2025-01-16 01:53:45,223 - INFO - Processing URL: https://www.todobravo.es/contacto/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.todobravo.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:45,936 - INFO - Found 1 emails in https://www.todobravo.es/contacto/
2025-01-16 01:53:45,936 - INFO - Processing valid email: info@todobravo.es
2025-01-16 01:53:45,944 - INFO - Extracted info - Name: Contacta con TodoBravo: Agencia de Diseño Web, Company: TodoBravo, Job: 
2025-01-16 01:53:46,134 - INFO - Added new lead: info@todobravo.es
2025-01-16 01:53:46,135 - INFO - Processing URL: https://digitalembassy.es/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'digitalembassy.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:46,504 - INFO - Found 1 emails in https://digitalembassy.es/
2025-01-16 01:53:46,504 - INFO - Processing valid email: info@digitalembassy.es
2025-01-16 01:53:46,511 - INFO - Extracted info - Name: , Company: Digital Embassy, Job: 
2025-01-16 01:53:46,918 - INFO - Added new lead: info@digitalembassy.es
2025-01-16 01:53:46,919 - INFO - Processing URL: http://www.serviceplan.com.es/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.serviceplan.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.serviceplan.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.house-of-communication.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:48,557 - INFO - Found 2 emails in http://www.serviceplan.com.es/
2025-01-16 01:53:48,557 - INFO - Processing valid email: mediaplus-madrid-dpo@house-of-communication.com
2025-01-16 01:53:48,570 - INFO - Extracted info - Name: Contacto, Company: Serviceplan, Job: Desde las relaciones públicas corporativas hasta el posicionamiento de los CEO y las relaciones con influencers: una estrategia de relaciones públicas bien pensada genera confianza.
2025-01-16 01:53:48,956 - INFO - Added new lead: mediaplus-madrid-dpo@house-of-communication.com
2025-01-16 01:53:48,956 - INFO - Processing valid email: crm@serviceplan.com
2025-01-16 01:53:48,956 - INFO - Processing URL: https://www.doubleyou.es/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.doubleyou.es'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'doubleyou.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:53:50,070 - INFO - Found 2 emails in https://www.doubleyou.es/
2025-01-16 01:53:50,070 - INFO - Processing valid email: protecciondatos@doubleyou.com
2025-01-16 01:53:50,073 - INFO - Extracted info - Name: Persona de contacto Barcelona, Company: DoubleYou, Job: 
2025-01-16 01:53:50,268 - INFO - Added new lead: protecciondatos@doubleyou.com
2025-01-16 01:53:50,268 - INFO - Processing valid email: info@doubleyou.com
2025-01-16 01:53:50,268 - INFO - Search completed. Found 13 total leads
INFO:     127.0.0.1:57337 - "POST /search HTTP/1.1" 200 OK
2025-01-16 01:55:47,837 - INFO - Received search request: search_terms=['marketing agency valencia'] num_results=3 ignore_previously_fetched=True optimize_english=False optimize_spanish=True shuffle_keywords=True language='ES' enable_email_sending=False from_email=None reply_to=None email_template_id=None
2025-01-16 01:55:47,837 - INFO - Shuffled search term: marketing valencia agency
2025-01-16 01:55:47,837 - INFO - Optimized search term: "marketing valencia agency" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:55:47,838 - INFO - Starting search for query: "marketing valencia agency" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:55:51,092 - INFO - Found 3 results
2025-01-16 01:55:51,092 - INFO - Found 3 URLs for term: "marketing valencia agency" correo OR contacto OR "ponte en contacto" site:.es
2025-01-16 01:55:51,092 - INFO - Processing URL: http://www.marketingcreativo.es/
2025-01-16 01:55:51,360 - INFO - Found 0 emails in http://www.marketingcreativo.es/
2025-01-16 01:55:51,360 - INFO - Processing URL: https://agenciaestimado.com/contacto/
/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'agenciaestimado.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2025-01-16 01:55:51,687 - INFO - Found 1 emails in https://agenciaestimado.com/contacto/
2025-01-16 01:55:51,688 - INFO - Processing valid email: contacto@agenciaestimado.com
2025-01-16 01:55:51,694 - INFO - Extracted info - Name: , Company: Agencia Estimado, Job: 
2025-01-16 01:55:52,089 - INFO - Added new lead: contacto@agenciaestimado.com
2025-01-16 01:55:52,089 - INFO - Processing URL: https://agenciaestimado.com/insight-lab/
2025-01-16 01:55:52,089 - INFO - Skipping already processed domain: agenciaestimado.com
2025-01-16 01:55:52,089 - INFO - Search completed. Found 1 total leads
INFO:     127.0.0.1:57620 - "POST /search HTTP/1.1" 200 OK
INFO:     127.0.0.1:57746 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:57746 - "GET / HTTP/1.1" 404 Not Found
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [30067]
2025-01-18 03:31:52,210 - root - ERROR - Unexpected error in database session: 'str' object has no attribute 'template_name'
2025-01-18 03:31:52,212 - root - ERROR - Page execution error
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 3436, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 1502, in manual_search_page
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 1502, in <listcomp>
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'template_name'
2025-01-18 03:45:55,419 - root - ERROR - Unexpected error in database session: 'str' object has no attribute 'template_name'
2025-01-18 03:45:55,422 - root - ERROR - Page execution error
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 3436, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 1502, in manual_search_page
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 1502, in <listcomp>
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'template_name'
2025-01-18 05:42:47,180 - __main__ - INFO - Database initialized successfully
2025-01-18 05:42:47,188 - __main__ - INFO - Application started successfully
2025-01-18 05:42:48,119 - __main__ - INFO - Database initialized successfully
2025-01-18 05:42:48,119 - root - INFO - Application started successfully
2025-01-18 05:43:16,309 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:43:16,310 - python_multipart.multipart - DEBUG - Calling on_field_name with data[0:12]
2025-01-18 05:43:16,310 - python_multipart.multipart - DEBUG - Calling on_field_data with data[13:17]
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_name with data[18:29]
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_data with data[30:31]
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_name with data[32:57]
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_data with data[58:62]
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_name with data[63:71]
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_data with data[72:74]
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:43:16,311 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-01-18 05:43:16,312 - root - INFO - Manual search request received: terms=test, num_results=1
2025-01-18 05:43:16,313 - root - INFO - Starting search for query: test
2025-01-18 05:43:16,319 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): www.google.com:443
2025-01-18 05:43:16,615 - urllib3.connectionpool - DEBUG - https://www.google.com:443 "GET /search?q=test&num=1&hl=ES&start=0 HTTP/1.1" 200 None
2025-01-18 05:43:16,653 - root - INFO - Found 0 valid results
2025-01-18 05:43:22,713 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_name with data[0:12]
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_data with data[13:32]
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_name with data[33:44]
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_data with data[45:46]
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_name with data[47:72]
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_data with data[73:77]
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_name with data[78:94]
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_data with data[95:99]
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_name with data[100:108]
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_data with data[109:111]
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:43:22,714 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-01-18 05:43:22,714 - root - INFO - Manual search request received: terms=inmobiliaria malaga, num_results=3
2025-01-18 05:43:22,715 - root - INFO - Starting search for query: "inmobiliaria malaga" email OR correo OR contacto OR "contactar" site:.es
2025-01-18 05:43:22,716 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): www.google.com:443
2025-01-18 05:43:22,960 - urllib3.connectionpool - DEBUG - https://www.google.com:443 "GET /search?q=%22inmobiliaria%20malaga%22%20email%20OR%20correo%20OR%20contacto%20OR%20%22contactar%22%20site:.es&num=3&hl=ES&start=0 HTTP/1.1" 200 None
2025-01-18 05:43:22,998 - root - INFO - Found 0 valid results
2025-01-18 05:44:43,515 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:44:43,515 - python_multipart.multipart - DEBUG - Calling on_field_name with data[0:12]
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_data with data[13:32]
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_name with data[33:44]
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_data with data[45:46]
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_name with data[47:72]
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_data with data[73:77]
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_name with data[78:94]
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_data with data[95:99]
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_name with data[100:108]
2025-01-18 05:44:43,516 - python_multipart.multipart - DEBUG - Calling on_field_data with data[109:111]
2025-01-18 05:44:43,517 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:44:43,517 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-01-18 05:44:43,518 - root - INFO - Manual search request received: terms=inmobiliaria malaga, num_results=3
2025-01-18 05:44:43,519 - root - INFO - Starting search for query: "inmobiliaria malaga" email OR correo OR contacto OR "contactar" site:.es
2025-01-18 05:44:43,521 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): www.google.com:443
2025-01-18 05:44:43,648 - urllib3.connectionpool - DEBUG - https://www.google.com:443 "GET /search?q=%22inmobiliaria%20malaga%22%20email%20OR%20correo%20OR%20contacto%20OR%20%22contactar%22%20site:.es&num=3&hl=ES&start=0 HTTP/1.1" 200 None
2025-01-18 05:44:43,687 - root - INFO - Found 0 valid results
2025-01-18 05:46:27,470 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:46:27,471 - python_multipart.multipart - DEBUG - Calling on_field_name with data[0:12]
2025-01-18 05:46:27,471 - python_multipart.multipart - DEBUG - Calling on_field_data with data[13:32]
2025-01-18 05:46:27,471 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:46:27,471 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:46:27,472 - python_multipart.multipart - DEBUG - Calling on_field_name with data[33:44]
2025-01-18 05:46:27,472 - python_multipart.multipart - DEBUG - Calling on_field_data with data[45:46]
2025-01-18 05:46:27,472 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:46:27,472 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:46:27,472 - python_multipart.multipart - DEBUG - Calling on_field_name with data[47:72]
2025-01-18 05:46:27,472 - python_multipart.multipart - DEBUG - Calling on_field_data with data[73:77]
2025-01-18 05:46:27,472 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:46:27,472 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:46:27,472 - python_multipart.multipart - DEBUG - Calling on_field_name with data[78:94]
2025-01-18 05:46:27,473 - python_multipart.multipart - DEBUG - Calling on_field_data with data[95:99]
2025-01-18 05:46:27,473 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:46:27,473 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:46:27,473 - python_multipart.multipart - DEBUG - Calling on_field_name with data[100:108]
2025-01-18 05:46:27,473 - python_multipart.multipart - DEBUG - Calling on_field_data with data[109:111]
2025-01-18 05:46:27,473 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:46:27,473 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-01-18 05:46:27,474 - root - INFO - Manual search request received: terms=inmobiliaria malaga, num_results=3
2025-01-18 05:46:27,475 - root - INFO - Starting search for query: "inmobiliaria malaga" email OR correo OR contacto OR "contactar" site:.es
2025-01-18 05:46:27,480 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): www.google.com:443
2025-01-18 05:46:27,734 - urllib3.connectionpool - DEBUG - https://www.google.com:443 "GET /search?q=%22inmobiliaria%20malaga%22%20email%20OR%20correo%20OR%20contacto%20OR%20%22contactar%22%20site:.es&num=3&hl=ES&start=0 HTTP/1.1" 200 None
2025-01-18 05:46:27,772 - root - INFO - Found 0 valid results
2025-01-18 05:47:34,324 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_name with data[0:12]
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_data with data[13:25]
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_name with data[26:37]
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_data with data[38:39]
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_name with data[40:48]
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_data with data[49:51]
2025-01-18 05:47:34,325 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:47:34,326 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-01-18 05:47:34,327 - root - INFO - Manual search request received: terms=inmobiliaria, num_results=2
2025-01-18 05:47:34,328 - root - INFO - Starting search for query: inmobiliaria
2025-01-18 05:47:34,331 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): www.google.com:443
2025-01-18 05:47:34,619 - urllib3.connectionpool - DEBUG - https://www.google.com:443 "GET /search?q=inmobiliaria&num=2&hl=ES&start=0 HTTP/1.1" 200 None
2025-01-18 05:47:34,729 - root - INFO - Found 0 valid results
2025-01-18 05:49:23,235 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_name with data[0:12]
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_data with data[13:25]
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_name with data[26:37]
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_data with data[38:39]
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_start with no data
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_name with data[40:48]
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_data with data[49:51]
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_field_end with no data
2025-01-18 05:49:23,236 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-01-18 05:49:23,237 - root - INFO - Manual search request received: terms=inmobiliaria, num_results=2
2025-01-18 05:49:23,239 - root - INFO - Starting search for query: inmobiliaria
2025-01-18 05:49:23,241 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): www.google.com:443
2025-01-18 05:49:23,357 - urllib3.connectionpool - DEBUG - https://www.google.com:443 "GET /search?q=inmobiliaria&num=2&hl=ES&start=0 HTTP/1.1" 200 None
2025-01-18 05:49:23,396 - root - INFO - Found 0 valid results
2025-01-18 05:50:58,377 - python_multipart.multipart - DEBUG - Calling on_part_begin with no data
2025-01-18 05:50:58,381 - python_multipart.multipart - DEBUG - Calling on_header_field with data[50:69]
2025-01-18 05:50:58,382 - python_multipart.multipart - DEBUG - Calling on_header_value with data[71:101]
2025-01-18 05:50:58,383 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-01-18 05:50:58,384 - python_multipart.multipart - DEBUG - Calling on_headers_finished with no data
2025-01-18 05:50:58,384 - python_multipart.multipart - DEBUG - Calling on_part_data with data[105:122]
2025-01-18 05:50:58,385 - python_multipart.multipart - DEBUG - Calling on_part_end with no data
2025-01-18 05:50:58,385 - python_multipart.multipart - DEBUG - Calling on_part_begin with no data
2025-01-18 05:50:58,385 - python_multipart.multipart - DEBUG - Calling on_header_field with data[174:193]
2025-01-18 05:50:58,386 - python_multipart.multipart - DEBUG - Calling on_header_value with data[195:224]
2025-01-18 05:50:58,387 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-01-18 05:50:58,387 - python_multipart.multipart - DEBUG - Calling on_headers_finished with no data
2025-01-18 05:50:58,387 - python_multipart.multipart - DEBUG - Calling on_part_data with data[228:229]
2025-01-18 05:50:58,388 - python_multipart.multipart - DEBUG - Calling on_part_end with no data
2025-01-18 05:50:58,389 - python_multipart.multipart - DEBUG - Calling on_part_begin with no data
2025-01-18 05:50:58,389 - python_multipart.multipart - DEBUG - Calling on_header_field with data[281:300]
2025-01-18 05:50:58,389 - python_multipart.multipart - DEBUG - Calling on_header_value with data[302:345]
2025-01-18 05:50:58,389 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-01-18 05:50:58,389 - python_multipart.multipart - DEBUG - Calling on_headers_finished with no data
2025-01-18 05:50:58,390 - python_multipart.multipart - DEBUG - Calling on_part_data with data[349:353]
2025-01-18 05:50:58,390 - python_multipart.multipart - DEBUG - Calling on_part_end with no data
2025-01-18 05:50:58,390 - python_multipart.multipart - DEBUG - Calling on_part_begin with no data
2025-01-18 05:50:58,390 - python_multipart.multipart - DEBUG - Calling on_header_field with data[405:424]
2025-01-18 05:50:58,390 - python_multipart.multipart - DEBUG - Calling on_header_value with data[426:460]
2025-01-18 05:50:58,390 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-01-18 05:50:58,390 - python_multipart.multipart - DEBUG - Calling on_headers_finished with no data
2025-01-18 05:50:58,390 - python_multipart.multipart - DEBUG - Calling on_part_data with data[464:468]
2025-01-18 05:50:58,391 - python_multipart.multipart - DEBUG - Calling on_part_end with no data
2025-01-18 05:50:58,391 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-01-18 05:50:58,393 - root - INFO - Manual search request received: terms=software engineer, num_results=5
2025-01-18 05:50:58,397 - root - INFO - Starting search for query: "software engineer" email OR contact OR "get in touch" site:.com
2025-01-18 05:50:58,407 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): www.google.com:443
2025-01-18 05:50:58,546 - urllib3.connectionpool - DEBUG - https://www.google.com:443 "GET /search?q=%22software%20engineer%22%20email%20OR%20contact%20OR%20%22get%20in%20touch%22%20site:.com&num=5&hl=ES&start=0 HTTP/1.1" 200 None
2025-01-18 05:50:58,586 - root - INFO - Found 0 valid results
2025-01-18 21:33:58,576 - __main__ - ERROR - Failed to connect to database: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:33:59,276 - __main__ - ERROR - Failed to connect to database: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:33:59,712 - __main__ - ERROR - Failed to connect to database: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:00,559 - __main__ - ERROR - Failed to connect to database: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,100 - __main__ - ERROR - Failed to connect to database: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,101 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,101 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,102 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,102 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,102 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,102 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,102 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,102 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,102 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,103 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,103 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,103 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,103 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,103 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,104 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,115 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,115 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,116 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,116 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,117 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,118 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,118 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,118 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,118 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,119 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,119 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,119 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,119 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,120 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,120 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,120 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,121 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,121 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,122 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,123 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,124 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,125 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,126 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,126 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,126 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,126 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,130 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,130 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,131 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,132 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,132 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,132 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,132 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,133 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,133 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,134 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,134 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,134 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,136 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,146 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,147 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,150 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,150 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,150 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,150 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,151 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,151 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,151 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,151 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,152 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,152 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,152 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,152 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:01,153 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:04,612 - __main__ - ERROR - Failed to connect to database: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:05,194 - __main__ - ERROR - Failed to connect to database: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,916 - __main__ - ERROR - Failed to connect to database: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,917 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,918 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,918 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,919 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,919 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,919 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,920 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,921 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,922 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,923 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,924 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,924 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,924 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,925 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,925 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,925 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,926 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,926 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,926 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,927 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,927 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,927 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,929 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,930 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,931 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,931 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,932 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,932 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,932 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,932 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,933 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,933 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,933 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,933 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,933 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,934 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,934 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,934 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,934 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,935 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,935 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,936 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,936 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,936 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,937 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,937 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,937 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,937 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,937 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,938 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,939 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,940 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,941 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,942 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,943 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,943 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,943 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,943 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,944 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,944 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,944 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,944 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,944 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,944 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,945 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,945 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,945 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,945 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,945 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,947 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,947 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,947 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,947 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,948 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,948 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,948 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,948 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,949 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,949 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,949 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,949 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,949 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,949 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,949 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,950 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,950 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,950 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,950 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,950 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,950 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,950 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,951 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,951 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,951 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,951 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,951 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,951 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,951 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,952 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,952 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,952 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,952 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,952 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,953 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,953 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,953 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,953 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:34:06,953 - __main__ - ERROR - Database session error: (psycopg2.OperationalError) connection to server at "aws-0-eu-central-1.pooler.supabase.com" (18.198.30.239), port 6543 failed: FATAL:  Max client connections reached

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-18 21:50:49,426 - root - ERROR - Google search error for 'escuela madrid chino': search() got an unexpected keyword argument 'stop'
2025-01-18 21:50:55,357 - root - ERROR - Google search error for 'academia escuela chino madrid': search() got an unexpected keyword argument 'stop'
2025-01-18 21:51:02,904 - root - ERROR - Google search error for 'madrid chino aprender': search() got an unexpected keyword argument 'stop'
2025-01-19 00:40:08,522 - root - ERROR - Email service check error: An error occurred (AccessDenied) when calling the GetSendQuota operation: User: arn:aws:iam::169297731852:user/ses is not authorized to perform: ses:GetSendQuota with an explicit deny in an identity-based policy
2025-01-19 00:40:11,130 - root - ERROR - An error occurred in the main function
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 3133, in main
    pages["🚀 Projects & Campaigns"]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 2211, in projects_campaigns_page
    active_project_id = session.query(Project.id).filter_by(project_name=active_project).scalar()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2825, in scalar
    ret = self.one()
          ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2798, in one
    return self._iter().one()  # type: ignore
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1532, in one
    return self._only_one_row(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 810, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when exactly one was required
2025-01-19 00:41:04,290 - root - ERROR - Email service check error: An error occurred (AccessDenied) when calling the GetSendQuota operation: User: arn:aws:iam::169297731852:user/ses is not authorized to perform: ses:GetSendQuota with an explicit deny in an identity-based policy
2025-01-19 00:41:05,872 - root - ERROR - An error occurred in the main function
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 3133, in main
    pages["🚀 Projects & Campaigns"]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 2211, in projects_campaigns_page
    active_project_id = session.query(Project.id).filter_by(project_name=active_project).scalar()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2825, in scalar
    ret = self.one()
          ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2798, in one
    return self._iter().one()  # type: ignore
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1532, in one
    return self._only_one_row(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 810, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when exactly one was required
2025-01-19 00:48:55,250 - root - ERROR - Unexpected error in database session: 'str' object has no attribute 'template_name'
2025-01-19 00:48:55,254 - root - ERROR - Page execution error
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 3436, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 1502, in manual_search_page
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 1502, in <listcomp>
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'template_name'
2025-01-19 00:52:11,262 - root - ERROR - Unexpected error in database session: 'str' object has no attribute 'template_name'
2025-01-19 00:52:11,267 - root - ERROR - Page execution error
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 3436, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 1502, in manual_search_page
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 1502, in <listcomp>
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'template_name'
2025-01-19 00:52:53,382 - root - ERROR - Unexpected error in database session: 'str' object has no attribute 'template_name'
2025-01-19 00:52:53,385 - root - ERROR - Page execution error
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 3436, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 1502, in manual_search_page
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 1502, in <listcomp>
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'template_name'
2025-01-19 01:43:22,808 - root - ERROR - An error occurred in the main function
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 2408, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 945, in manual_search_page
    search_terms=st_tags(label='Enter search terms:',text='Press enter to add more',value=st.session_state.search_terms,suggestions=[term.term for term in all_search_terms],maxtags=10,key='search_terms_input')
                                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 945, in <listcomp>
    search_terms=st_tags(label='Enter search terms:',text='Press enter to add more',value=st.session_state.search_terms,suggestions=[term.term for term in all_search_terms],maxtags=10,key='search_terms_input')
                                                                                                                                     ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 1584, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <SearchTerm at 0x17377b0d0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-01-19 01:50:50,661 - root - ERROR - An error occurred in the main function
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 2334, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 937, in manual_search_page
    email_template = st.selectbox("Email template", options=email_templates, format_func=lambda x: x.split(":")[1].strip())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 245, in selectbox
    return self._selectbox(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in _selectbox
    options=[str(format_func(option)) for option in opt],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in <listcomp>
    options=[str(format_func(option)) for option in opt],
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 937, in <lambda>
    email_template = st.selectbox("Email template", options=email_templates, format_func=lambda x: x.split(":")[1].strip())
                                                                                                   ^^^^^^^
AttributeError: 'EmailTemplate' object has no attribute 'split'
2025-01-19 01:50:53,814 - root - ERROR - An error occurred in the main function
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 2334, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 937, in manual_search_page
    email_template = st.selectbox("Email template", options=email_templates, format_func=lambda x: x.split(":")[1].strip())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 245, in selectbox
    return self._selectbox(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in _selectbox
    options=[str(format_func(option)) for option in opt],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in <listcomp>
    options=[str(format_func(option)) for option in opt],
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 937, in <lambda>
    email_template = st.selectbox("Email template", options=email_templates, format_func=lambda x: x.split(":")[1].strip())
                                                                                                   ^^^^^^^
AttributeError: 'EmailTemplate' object has no attribute 'split'
2025-01-19 01:51:59,782 - root - ERROR - An error occurred in the main function
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 2339, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 937, in manual_search_page
    email_template = st.selectbox(
                     ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 245, in selectbox
    return self._selectbox(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in _selectbox
    options=[str(format_func(option)) for option in opt],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in <listcomp>
    options=[str(format_func(option)) for option in opt],
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 940, in <lambda>
    format_func=lambda t: f"{t.id}: {t.template_name}",
                             ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 1584, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <EmailTemplate at 0x173c51650> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-01-19 01:52:03,046 - root - ERROR - An error occurred in the main function
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 2339, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 937, in manual_search_page
    email_template = st.selectbox(
                     ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 245, in selectbox
    return self._selectbox(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in _selectbox
    options=[str(format_func(option)) for option in opt],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in <listcomp>
    options=[str(format_func(option)) for option in opt],
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 940, in <lambda>
    format_func=lambda t: f"{t.id}: {t.template_name}",
                             ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 1584, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <EmailTemplate at 0x1714118d0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-01-19 01:52:57,611 - root - ERROR - An error occurred in the main function
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 2346, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 937, in manual_search_page
    template = st.selectbox(
               ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 245, in selectbox
    return self._selectbox(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in _selectbox
    options=[str(format_func(option)) for option in opt],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in <listcomp>
    options=[str(format_func(option)) for option in opt],
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 940, in <lambda>
    format_func=lambda t: f"{t.id}: {t.template_name}",
                             ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 1584, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <EmailTemplate at 0x174975950> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-01-19 01:53:01,288 - root - ERROR - An error occurred in the main function
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 2346, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 937, in manual_search_page
    template = st.selectbox(
               ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 245, in selectbox
    return self._selectbox(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in _selectbox
    options=[str(format_func(option)) for option in opt],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/elements/widgets/selectbox.py", line 296, in <listcomp>
    options=[str(format_func(option)) for option in opt],
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app.py", line 940, in <lambda>
    format_func=lambda t: f"{t.id}: {t.template_name}",
                             ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 1584, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <EmailTemplate at 0x1714e9ed0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-01-20 03:53:51,011 - root - ERROR - Unexpected error in database session: 'str' object has no attribute 'template_name'
2025-01-20 03:53:51,032 - root - ERROR - Page execution error
Traceback (most recent call last):
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app copy.py", line 3436, in main
    pages[selected]()
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app copy.py", line 1502, in manual_search_page
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samihalawa/git/FINAL-email-crawler-streamlit-final-1/streamlit_app copy.py", line 1502, in <listcomp>
    template_details = "\n".join([f"- {t.template_name}" for t in email_templates])
                                       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'template_name'
